name: Wails build

on: [push]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build: [
                    { name: test-wails, platform: linux/amd64, os: ubuntu-latest },
                    { name: test-wails, platform: darwin/universal, os: macos-latest }
                ]
        runs-on: ${{ matrix.build.os }}
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   uses: dAppServer/wails-build-action@v2.2
                with:
                    build-name: ${{ matrix.build.name }}
                    build-platform: ${{ matrix.build.platform }}
                    sign: false
